#!/usr/bin/env python

import xmlrpclib

server="localhost"
user="lliurex"
password="lliurex"

c=xmlrpclib.ServerProxy("https://"+server+":9779")
user=(user,password)
#print c.get_methods('NetinstallManager')

#se necesitan las siguientes variables del n4d-dnsmasq
#INTERNAL_DOMAIN
#HOSTNAME

# se puede lanzar después del Dnsmasq
print c.load_exports(user,"NetinstallManager")
